# this sets the logger level (true = info, false = debug)
environment: production

# ethereum node urls
eth_rpc_url: <holesky_rpc_url>

# avs service manager proxy address (holesky testnet)
avs_service_manager_address: 0xdE93E0dA148e1919bb7f33cd8847F96e45791210

# ecdsa private key store path and password
ecdsa_private_key_store_path: ~/.eigenlayer/aggregator/test.ecdsa.key.json

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
node_eigen_api_server_host_and_port: 0.0.0.0:8080
eigen_metrics_ip_port_address: 0.0.0.0:9090

# grpc server for communication in between operator and aggregator
node_task_server_host_and_port: 0.0.0.0:9010

# grpc server on which the operator receives tasks
node_task_server_host_and_port_to_broadcast: <your_public_ip_address>:9010

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: holesky.task.aethos.network:50051

# operator id (your operator public address)
operator_id: operator-xyz