# this sets the logger level (true = info, false = debug)
environment: production

eth_rpc_url: http://localhost:8545
eth_ws_url: ws://localhost:8545

ecdsa_private_key_store_path: ~/.eigenlayer/operator/test.ecdsa.key.json

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
enable_node_api: true
node_eigen_api_server_host_and_port: localhost:8080
enable_metrics: true
eigen_metrics_ip_port_address: localhost:9090

# grpc server for communication in between operator and aggregator
node_task_server_host_and_port: localhost:9010

# grpc server on which the operator listens for messages from the aggregator
node_task_server_host_and_port_to_broadcast: localhost:9010

operator_id: operator-1
aggregator_server_ip_port_address: localhost:50051
