# this sets the logger level (true = info, false = debug)
environment: production

# ecdsa private key store path and password
ecdsa_private_key_store_path: ~/.eigenlayer/aggregator/test.ecdsa.key.json

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
enable_node_api: true
node_eigen_api_server_host_and_port: 0.0.0.0:8080
enable_metrics: true
eigen_metrics_ip_port_address: 0.0.0.0:9090

# grpc server for communication in between operator and aggregator 
node_task_server_host_and_port: 0.0.0.0:9010

# grpc server on which the operator listens for messages from the aggregator
node_task_server_host_and_port_to_broadcast: 0.0.0.0:9010

operator_id: operator-1

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: 34.41.39.208:50051
