# this sets the logger level 
environment: production

# ethereum node urls
eth_rpc_url: <eth_rpc_url>

# avs service manager proxy address 
avs_service_manager_address: <aethos_avs_servicemanager_address>[see readme]
# avs directory address (eigenlayer holesky testnet)
avs_directory_address: <eigenlayer_avs_directory_address>[see readme]

# registration private key store path and password
registration_private_key_store_path: <path_to_private_key_store>
registration_private_key_password: <password>

# aethos signing private key store path and password
aethos_signing_private_key_store_path: <path_to_private_key_store>
aethos_signing_private_key_password: <password>

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
node_eigen_api_server_host_and_port: 0.0.0.0:8080
eigen_metrics_ip_port_address: 0.0.0.0:9090

# grpc server for communication in between operator and aggregator
node_task_server_host_and_port: 0.0.0.0:9010

# grpc server on which the operator receives tasks
node_task_server_host_and_port_to_broadcast: <your_public_ip_address>:9010

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: <aggregator_dns_name>[see readme]

# db path
db_path: /app/data/

# enable log colors
enable_log_color: true