# this sets the logger level 
environment: production

# avs service manager proxy address 
avs_service_manager_address: 0xdE93E0dA148e1919bb7f33cd8847F96e45791210
# avs directory address (eigenlayer holesky testnet)
avs_directory_address: 0x055733000064333CaDDbC92763c58BF0192fFeBf

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
node_eigen_api_server_host_and_port: 0.0.0.0:8080
eigen_metrics_ip_port_address: 0.0.0.0:9090

# grpc server for communication in between operator and aggregator
node_task_server_host_and_port: 0.0.0.0:9010

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: holesky.task.aethos.network:50051

# db path
db_path: /app/data/

# enable log colors
enable_log_color: true

####### TODO: Operators please update below values for your node ##############

# TODO: ECDSA Key for EigenLayer Operator Registration
registration_private_key_store_path: <path_to_private_key_store>
registration_private_key_password: <password>

# TODO: ECDSA Key for Aethos Task Signing
aethos_signing_private_key_store_path: <path_to_private_key_store>
aethos_signing_private_key_password: <password>

# TODO: Provide a working Ethereum RPC URL
eth_rpc_url: <eth_rpc_url>

# TODO: Provide IP and port to broadcast to Aethos for tasks
# Note: Must route traffic to the node's NODE_TASK_SERVER_HOST_AND_PORT
# Note: Ensure traffic from Aethos IP (18.118.236.196:9010/tcp) is whitelisted to pass health check
node_task_server_host_and_port_to_broadcast: <your_public_ip_address>:9010